import { getInstrumentProfile, instrumentProfiles } from "./instrumentProfiles.js";

const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const id = () => `evt-${Date.now().toString(36)}-${Math.random().toString(16).slice(2, 8)}`;

let activeEvents = [];

const templates = [
  { type: "MARKET_NEWS", scope: "MARKET", headline: "Simulated Event: market sentiment improves after broad demand update", sentimentImpact: 14, demandImpact: 8, liquidityImpact: 2, volatilityImpact: 4, severity: "MEDIUM" },
  { type: "MARKET_NEWS", scope: "MARKET", headline: "Simulated Event: market turns cautious after macro uncertainty", sentimentImpact: -16, demandImpact: -10, liquidityImpact: -4, volatilityImpact: 14, severity: "MEDIUM" },
  { type: "SECTOR_NEWS", scope: "SECTOR", sector: "Technology", headline: "Simulated Event: technology stocks move together after demand repricing", sentimentImpact: 18, demandImpact: 12, liquidityImpact: 0, volatilityImpact: 10, severity: "HIGH" },
  { type: "SECTOR_NEWS", scope: "SECTOR", sector: "Financials", headline: "Simulated Event: financial stocks face cautious sentiment", sentimentImpact: -13, demandImpact: -9, liquidityImpact: -3, volatilityImpact: 8, severity: "MEDIUM" },
  { type: "LIQUIDITY_SHOCK", scope: "MARKET", headline: "Simulated Event: liquidity thins across the practice market", sentimentImpact: -4, demandImpact: -5, liquidityImpact: -18, volatilityImpact: 18, severity: "HIGH" },
];

export const createMarketEvent = ({
  type = "MARKET_NEWS",
  scope = "MARKET",
  ticker = null,
  sector = null,
  headline,
  description,
  sentimentImpact = 0,
  demandImpact = 0,
  liquidityImpact = 0,
  volatilityImpact = 0,
  createdTick = 0,
  durationTicks = 45,
  severity = "LOW",
  visibleToUsers = true,
} = {}) => ({
  id: id(),
  type,
  scope,
  ticker,
  sector,
  headline: headline || "Simulated Event: practice-market conditions changed",
  description: description || "Generated by the StockBreakers simulation engine.",
  sentimentImpact: clamp(Number(sentimentImpact || 0), -50, 50),
  demandImpact: clamp(Number(demandImpact || 0), -50, 50),
  liquidityImpact: clamp(Number(liquidityImpact || 0), -50, 50),
  volatilityImpact: clamp(Number(volatilityImpact || 0), -50, 50),
  createdTick,
  expiresTick: createdTick + Math.max(3, Number(durationTicks || 45)),
  decayRate: 0.94,
  currentImpact: {
    sentiment: clamp(Number(sentimentImpact || 0), -50, 50),
    demand: clamp(Number(demandImpact || 0), -50, 50),
    liquidity: clamp(Number(liquidityImpact || 0), -50, 50),
    volatility: clamp(Number(volatilityImpact || 0), -50, 50),
  },
  severity,
  visibleToUsers,
});

export const addMarketEvent = (payload = {}) => {
  const event = createMarketEvent(payload);
  activeEvents.push(event);
  return event;
};

export const maybeGenerateEvents = (clock, marketState) => {
  if (clock.tick < 2) return activeEvents;

  if (clock.lastEvent === "MARKET_OPEN" && clock.tick % 2 === 0) {
    const profile = instrumentProfiles[clock.tick % instrumentProfiles.length];
    activeEvents.push(createMarketEvent({
      type: "TICKER_NEWS",
      scope: "TICKER",
      ticker: profile.ticker,
      headline: `Simulated Event: ${profile.ticker} sees practice-market attention at the open`,
      sentimentImpact: profile.investorConfidence >= 0 ? 10 : -8,
      demandImpact: 10,
      volatilityImpact: 7,
      createdTick: clock.tick,
      durationTicks: 36,
      severity: "MEDIUM",
    }));
  }

  if (clock.tick % 41 === 0 || marketState.volatilityRegime === "NEWS_SHOCK") {
    const template = templates[clock.tick % templates.length];
    activeEvents.push(createMarketEvent({ ...template, createdTick: clock.tick, durationTicks: template.severity === "HIGH" ? 60 : 42 }));
  }

  return activeEvents;
};

export const decayEvents = (clock) => {
  activeEvents = activeEvents
    .filter((event) => event.expiresTick > clock.tick)
    .map((event) => {
      const age = Math.max(0, clock.tick - event.createdTick);
      const decay = Math.pow(event.decayRate, age);
      return {
        ...event,
        currentImpact: {
          sentiment: event.sentimentImpact * decay,
          demand: event.demandImpact * decay,
          liquidity: event.liquidityImpact * decay,
          volatility: event.volatilityImpact * decay,
        },
      };
    });
  return getActiveEvents();
};

export const generateEarningsEvent = (ticker, clock) => {
  const profile = getInstrumentProfile(ticker);
  if (!profile) return null;
  const expectedScore = clamp(60 + profile.investorConfidence * 0.25, 0, 100);
  const actualScore = clamp(expectedScore + Math.sin(clock.tick + profile.price) * 18, 0, 100);
  const surprise = actualScore - expectedScore;
  const event = createMarketEvent({
    type: "EARNINGS",
    scope: "TICKER",
    ticker: profile.ticker,
    headline: `Simulated Event: ${profile.ticker} earnings-like score ${surprise >= 0 ? "beats" : "misses"} expectation by ${Math.abs(surprise).toFixed(1)}`,
    description: "Uses simulated scores only. No real earnings or EPS data is used.",
    sentimentImpact: clamp(surprise * 1.3, -30, 30),
    demandImpact: clamp(surprise, -24, 24),
    volatilityImpact: 14,
    createdTick: clock.tick,
    durationTicks: 72,
    severity: Math.abs(surprise) > 10 ? "HIGH" : "MEDIUM",
  });
  activeEvents.push(event);
  return event;
};

export const tickEventEngine = (clock, marketState) => {
  decayEvents(clock);
  maybeGenerateEvents(clock, marketState);
  if (clock.lastEvent === "MARKET_OPEN" && clock.tick % 3 === 0) {
    generateEarningsEvent(instrumentProfiles[clock.tick % instrumentProfiles.length].ticker, clock);
  }
  return getActiveEvents();
};

export const getActiveEvents = ({ ticker, sector } = {}) =>
  activeEvents.filter((event) => {
    if (!event.visibleToUsers) return false;
    if (ticker) {
      const profile = getInstrumentProfile(ticker);
      return event.scope === "MARKET" || event.ticker === ticker || (event.scope === "SECTOR" && profile?.sector === event.sector);
    }
    if (sector) return event.scope === "MARKET" || event.sector === sector;
    return true;
  });

export const getEventImpactFor = (profile) => getActiveEvents({ ticker: profile.ticker }).reduce(
  (impact, event) => ({
    sentiment: impact.sentiment + Number(event.currentImpact?.sentiment || 0),
    demand: impact.demand + Number(event.currentImpact?.demand || 0),
    liquidity: impact.liquidity + Number(event.currentImpact?.liquidity || 0),
    volatility: impact.volatility + Number(event.currentImpact?.volatility || 0),
    count: impact.count + 1,
  }),
  { sentiment: 0, demand: 0, liquidity: 0, volatility: 0, count: 0 }
);

export const resetEvents = () => {
  activeEvents = [];
  return activeEvents;
};
