export const instrumentProfiles = [
  { ticker: "AAPL", name: "Apple Inc.", companyName: "Apple Inc.", price: 189.5, sector: "Technology", industry: "Consumer Devices", marketCapBucket: "LARGE", style: "QUALITY", baseVolatility: "NORMAL", liquidityScore: 92, betaToMarket: 1.1, innovationPotential: 28, investorConfidence: 24, tradingDemand: 18, baseSpreadBps: 4, averageVolume: 1200000, benchmarkWeight: 0.09 },
  { ticker: "MSFT", name: "Microsoft Corp.", companyName: "Microsoft Corp.", price: 415.2, sector: "Technology", industry: "Software", marketCapBucket: "LARGE", style: "QUALITY", baseVolatility: "LOW", liquidityScore: 94, betaToMarket: 1.0, innovationPotential: 26, investorConfidence: 30, tradingDemand: 14, baseSpreadBps: 4, averageVolume: 1050000, benchmarkWeight: 0.09 },
  { ticker: "GOOGL", name: "Alphabet Inc.", companyName: "Alphabet Inc.", price: 175.8, sector: "Technology", industry: "Internet", marketCapBucket: "LARGE", style: "GROWTH", baseVolatility: "NORMAL", liquidityScore: 90, betaToMarket: 1.05, innovationPotential: 24, investorConfidence: 18, tradingDemand: 10, baseSpreadBps: 5, averageVolume: 960000, benchmarkWeight: 0.08 },
  { ticker: "AMZN", name: "Amazon.com Inc.", companyName: "Amazon.com Inc.", price: 195.6, sector: "Consumer", industry: "E-commerce", marketCapBucket: "LARGE", style: "GROWTH", baseVolatility: "NORMAL", liquidityScore: 88, betaToMarket: 1.18, innovationPotential: 22, investorConfidence: 14, tradingDemand: 16, baseSpreadBps: 6, averageVolume: 980000, benchmarkWeight: 0.07 },
  { ticker: "TSLA", name: "Tesla Inc.", companyName: "Tesla Inc.", price: 245.1, sector: "Automotive", industry: "Electric Vehicles", marketCapBucket: "LARGE", style: "SPECULATIVE", baseVolatility: "HIGH", liquidityScore: 80, betaToMarket: 1.8, innovationPotential: 40, investorConfidence: 5, tradingDemand: 25, baseSpreadBps: 9, averageVolume: 1450000, benchmarkWeight: 0.06 },
  { ticker: "NVDA", name: "NVIDIA Corp.", companyName: "NVIDIA Corp.", price: 875.4, sector: "Technology", industry: "Semiconductors", marketCapBucket: "LARGE", style: "GROWTH", baseVolatility: "HIGH", liquidityScore: 88, betaToMarket: 1.55, innovationPotential: 44, investorConfidence: 22, tradingDemand: 30, baseSpreadBps: 8, averageVolume: 1700000, benchmarkWeight: 0.08 },
  { ticker: "META", name: "Meta Platforms", companyName: "Meta Platforms", price: 505.3, sector: "Technology", industry: "Social Platforms", marketCapBucket: "LARGE", style: "GROWTH", baseVolatility: "NORMAL", liquidityScore: 86, betaToMarket: 1.28, innovationPotential: 20, investorConfidence: 12, tradingDemand: 16, baseSpreadBps: 7, averageVolume: 840000, benchmarkWeight: 0.06 },
  { ticker: "JPM", name: "JPMorgan Chase", companyName: "JPMorgan Chase", price: 198.7, sector: "Financials", industry: "Banking", marketCapBucket: "LARGE", style: "VALUE", baseVolatility: "LOW", liquidityScore: 90, betaToMarket: 0.95, innovationPotential: 3, investorConfidence: 18, tradingDemand: 8, baseSpreadBps: 5, averageVolume: 720000, benchmarkWeight: 0.06 },
  { ticker: "JNJ", name: "Johnson & Johnson", companyName: "Johnson & Johnson", price: 152.4, sector: "Healthcare", industry: "Pharma", marketCapBucket: "LARGE", style: "DIVIDEND", baseVolatility: "LOW", liquidityScore: 86, betaToMarket: 0.55, innovationPotential: 6, investorConfidence: 20, tradingDemand: 2, baseSpreadBps: 5, averageVolume: 560000, benchmarkWeight: 0.05 },
  { ticker: "V", name: "Visa Inc.", companyName: "Visa Inc.", price: 275.9, sector: "Financials", industry: "Payments", marketCapBucket: "LARGE", style: "QUALITY", baseVolatility: "LOW", liquidityScore: 90, betaToMarket: 0.9, innovationPotential: 12, investorConfidence: 24, tradingDemand: 9, baseSpreadBps: 5, averageVolume: 520000, benchmarkWeight: 0.05 },
  { ticker: "WMT", name: "Walmart Inc.", companyName: "Walmart Inc.", price: 68.5, sector: "Consumer", industry: "Retail", marketCapBucket: "LARGE", style: "DIVIDEND", baseVolatility: "LOW", liquidityScore: 86, betaToMarket: 0.45, innovationPotential: 2, investorConfidence: 16, tradingDemand: 4, baseSpreadBps: 5, averageVolume: 780000, benchmarkWeight: 0.05 },
  { ticker: "DIS", name: "Walt Disney Co.", companyName: "Walt Disney Co.", price: 112.3, sector: "Entertainment", industry: "Media", marketCapBucket: "LARGE", style: "VALUE", baseVolatility: "NORMAL", liquidityScore: 78, betaToMarket: 1.2, innovationPotential: 8, investorConfidence: 0, tradingDemand: 6, baseSpreadBps: 8, averageVolume: 620000, benchmarkWeight: 0.04 },
  { ticker: "NFLX", name: "Netflix Inc.", companyName: "Netflix Inc.", price: 635.8, sector: "Entertainment", industry: "Streaming", marketCapBucket: "LARGE", style: "GROWTH", baseVolatility: "HIGH", liquidityScore: 80, betaToMarket: 1.35, innovationPotential: 15, investorConfidence: 8, tradingDemand: 12, baseSpreadBps: 9, averageVolume: 680000, benchmarkWeight: 0.04 },
  { ticker: "COIN", name: "Coinbase Global", companyName: "Coinbase Global", price: 225.6, sector: "Financials", industry: "Crypto Infrastructure", marketCapBucket: "MID", style: "SPECULATIVE", baseVolatility: "EXTREME", liquidityScore: 68, betaToMarket: 2.2, innovationPotential: 24, investorConfidence: -8, tradingDemand: 22, baseSpreadBps: 16, averageVolume: 740000, benchmarkWeight: 0.03 },
  { ticker: "PLTR", name: "Palantir Technologies", companyName: "Palantir Technologies", price: 24.8, sector: "Technology", industry: "Data Platforms", marketCapBucket: "MID", style: "SPECULATIVE", baseVolatility: "EXTREME", liquidityScore: 72, betaToMarket: 1.9, innovationPotential: 32, investorConfidence: -2, tradingDemand: 24, baseSpreadBps: 14, averageVolume: 1100000, benchmarkWeight: 0.04 },
];

export const getInstrumentProfile = (ticker) =>
  instrumentProfiles.find((profile) => profile.ticker === String(ticker || "").toUpperCase()) || null;

export const volatilityMultiplierFor = (volatility) => ({
  LOW: 0.65,
  NORMAL: 1,
  HIGH: 1.75,
  EXTREME: 2.35,
}[volatility] || 1);

